server:
  port: 8081
spring:
  application:
    name: surveillance-service
  datasource:
    url: jdbc:postgresql://postgres_surv:5432/surveillance_db
    username: postgres
    password: "Bac.2020"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: alertes-topic
info:
  app: Surveillance Service
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: "always"
  health:
    kafka:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com.example.surveillance: DEBUG
    org.springframework.kafka: INFO
